### ISSUE TITLE
Reposting - Why is finality required?

### ISSUE THREAD

**Issue by jollysean** [ethereum/casper#30]
Hi,

I am AI developer and quite newer in ETH with only 2 years of experience.
My doubt is about finality for why have we developed such an elaborate mechanism which could have been done by timestamping each block(which happens already) and not accepting blocks beyond their destined timestamp. In PoS, generation time is predictable with minor latency.
Question in ETH forum is here: http://forum.ethereum.org/discussion/16449/finality-in-casper-pos-why-is-it-required#latest

**Comment by djrtwo** [comment]
Hi! Sorry no one got to this earlier. Finality is required for full PoS to prevent long-range attacks. It is a nice add-on to PoW. Because ethereum is currently a PoW chain, a hybrid PoW/PoS transition will be smoother than a full switch so we decided to layer PoS finality on top of PoW block proposals. After things are stable, we will switch to full PoS with PoS block proposals and finality.

As for simple time-stamping... a node using a timestamp to lock in a block at a given time does not represent the consensus of the validator set, it just represents whatever they happened to have received from the network at a given time and would open a node up to a number of attacks because PoS blocks can be cheaply created by an attacker (as opposed to expensive PoW blocks).

If you want more details, I suggest checking out the /r/ethereum subreddit or the ethresear.ch forum. The ethereum.org forum isn't the best place for this type of discussion. Sorry for the confusion!

CC: @karlfloersch @ChihChengLiang Please close this issue.
